### ISSUE TITLE
Is it possible to add an angular-ui uib-typeahead bootstrap v.3 to this extension?

### ISSUE THREAD

**Issue by Radu3000** [greysonp/todomvc-extension#2]
I have tried to do so here and didn't get far 
http://stackoverflow.com/questions/35180082/can-i-use-angular-ui-typeahead-in-a-chrome-extension

Thanks,
Radu

**Comment by greysonp** [comment]
You can definitely use angular and angular libraries in chrome extensions. This extension uses angular. There's no reason for me to add that library to this extension. I also don't maintain the majority of this codebase. The actual todo application is maintained by TodoMVC, not me. I just made an extension around it. You can find that project [here](https://github.com/tastejs/todomvc/tree/gh-pages/examples/angularjs).
